app/blueprints/home/models.py
from app import db
from datetime import datetime

class Vacation(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    plan_name = db.Column(db.String(50), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    guests = db.Column(db.Integer, nullable=False)
    date_leaving = db.Column(db.Date, nullable=False)
    date_returning = db.Column(db.Date, nullable=False)
    budget = db.Column(db.Float, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f"<Plan Name | {self.plan_name}>"

    def update(self, **kwargs):
        for key, value in kwargs.items():
            if key in {'plan_name','location','guests','date_leaving','date_returning','budget'}:
                setattr(self, key, value)
            db.session.commit()
    
    def delete(self):
        db.session.delete(self)
        db.session.commit()

app/blueprints/home/forms.py
from app import db, login
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField, IntegerField, FloatField
from wtforms.validators import DataRequired


class VacationForm(FlaskForm):
    location = StringField('Location', validators=[DataRequired()])
    plan_name = StringField('Vacation Plan Name')
    guests = IntegerField('Additonal Guests')
    date_leaving = DateField('Date Leaving')
    date_returning = DateField('Date Returning')
    budget = FloatField('Budget')
    submit = SubmitField('Submit')


    
    
    
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate 
from flask_login import LoginManager 
from config import Config 
from flask_wtf.csrf import CSRFProtect

app = Flask(__name__)
app.config.from_object(Config)


db = SQLAlchemy(app)
migrate = Migrate(app, db)
# compare_type=True
# Leave this when modifying the database, otherwise it doesn't recognize small changes

login = LoginManager(app)
login.login_view = 'auth.login' # Set this to your login page
login.login_message_category = 'danger'

from app.blueprints.auth import auth 
app.register_blueprint(auth)

from app.blueprints.home import home 
app.register_blueprint(home)

from app import routes

app/blueprints/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__, url_prefix='/home')

from . import routes, models

app/blueprints/home/routes.py
from . import home as h
from flask import render_template, redirect, flash, url_for
from flask_login import login_required, current_user
from . import home
from .forms import VacationForm
from .models import Vacation
from validators import url

@h.route('/')
def index():
    title = 'Home'

    return render_template('index.html', title = title)

@h.route('/vacation-planner')
@login_required
def vacationplanner():
    title = 'Vacation Planner'
    vacations = Vacation.query.all()
    return render_template('vacation_planner.html', title = title, vacations=vacations)
    
@h.route('/create-vacation-planner', methods = ['GET', 'POST'])
@login_required
def createvacationplanner():
    title = 'Create Vacation Planner'
    form = VacationForm()

    if form.validate_on_submit():
        plan_name = form.plan_name.data
        location = form.location.data
        guests = form.guests.data
        date_leaving = form.date_leaving.data
        date_returning = form.date_returning.data
        budget = form.budget.data
        new_plan = Vacation(plan_name=plan_name,location=location,guests=guests,date_leaving=date_leaving,date_returning=date_returning,budget=budget, user_id = current_user.id)
        flash(f"{plan_name} has been created!", "success")
        return redirect(url_for('index'))
    return render_template('create_vacation_planner.html', title = title, form = form)

@h.route('/edit-vacation/<vacation_id>', methods=["GET", "POST"])
@login_required 
def edit_vacation(vacation_id):
    vacation = Vacation.query.get_or_404(vacation_id)
    #Check if the user trying to edit the post is the current user
    if vacation.user_id != current_user.id:
        flash("You do not have edit access for this contact.", "danger")
        return redirect(url_for('index'))
    title = f"Edit Vacation: {{ Vacation.plan_name }}"
    form = VacationForm()
    if form.validate_on_submit():
        vacation.update(**form.data)
        flash(f"{vacation.plan_name} has been updated.", "success")
        return redirect(url_for('home.index'))
    return render_template('vacation_edit.html', title=title, vacation=vacation, form=form)

@h.route('/delete_vacation/<vacation_id>')
@login_required
def delete_contact(vacation_id):
    vacation = Vacation.query.get_or_404(vacation_id)
    if vacation.user_id != current_user.id:
        flash("You do not have delete access to this post.", 'secondary')
    else:
        vacation.delete()
        flash(f"{vacation} has been removed.", 'secondary')
    return redirect(url_for('home.index'))

app/routes.py
from app import app
from flask import redirect, url_for

@app.route('/') 
def index():
    return redirect(url_for('home.index'))

app/templates/alert_message.html
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="div alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="Description" content="Enter your description here"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <!-- <link rel="stylesheet" href="assets/css/style.css"> -->
        <title>Vacation Planner | {{ title }}</title>
    </head>
    <body class="bg-dark" style="height: 100vh;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom border-secondary">
            <div class="container-fluid">
                <a class="navbar-brand" href="">@Kelvin 2022</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('home.index') }}">Home</a>
                        <a class="nav-link" href="{{ url_for('home.vacationplanner') }}">Vacation Planner</a>
                        {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('home.createvacationplanner') }}">Create a Vacation Planner</a>
                        {% endif %}
                    </div>
                    <div class="navbar-nav mx-3">
                        {% if current_user.is_authenticated %}
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out</a>
                        {% else %}
                        <a class="nav-link justify-self-end" href="{{ url_for('auth.signup') }}">Sign Up</a>
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        <div class="container">
            {% include 'alert_message.html' %}
            {% block content %}

            {% endblock content %}
        </div>




        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
    </body>
</html>

app/templates/create_vacation_planner.html
{% extends 'base.html' %}

{% block content %}

<div class="row justify-content-center mt-5">
    <div class="col-4">
        <form method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.plan_name.label }}
                {{ form.plan_name(class="form-control", placeholder="Name of your Vacation Plan") }}
                
                {{ form.location.label}}
                {{ form.location(class="form-control", placeholder="Location") }}
                
                {{ form.guests.label}}
                {{ form.guests(class="form-control", placeholder="How Many Guests are Coming?") }}
                
                {{ form.date_leaving.label}}
                {{ form.date_leaving(class="form-control", placeholder="When are you leaving?") }}
                
                {{ form.date_returning.label}}
                {{ form.date_returning(class="form-control", placeholder="When are you returning?") }}
                
                {{ form.budget.label}}
                {{ form.budget(class="form-control", placeholder="What is your budget?") }}
                
                {{ form.submit(class="btn btn-primary mt-2") }}
            </div>
        </form>
    </div>
</div>

{% endblock content %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="card pt-3">
    <div class="card-body">
      {% if current_user.is_authenticated %}    
      <p>Hello {{(current_user)}} Thank you for using this program!</p>
      {% else %}
      <p>Please Sign In to access your Vacation Book</p>
      {% endif %}
    </div>
  </div>

{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-4">
            <form method="post">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.username.label}}
                    {{ form.username(class="form-control", placeholder="Username") }}

                    {{ form.password.label }}
                    {{ form.password(class="form-control", placeholder="Password") }}

                    {{ form.submit(class="btn btn-primary mt-2") }}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

app/templates/other/map.html
<iframe
  width="600"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDJSUgd9hmIf0aQ5NPPM1N45TZSJIFMwuI
    &q=Space+Needle,Seattle+WA">
</iframe>

app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-4">
            <form method="post">
                {{ form.csrf_token }}
                <div class="form-group">
                        {{ form.email.label }}
                        {{ form.email(class="form-control", placeholder="Email") }}

                        {{ form.username.label }}
                        {{ form.username(class="form-control", placeholder="Username") }}

                        {{ form.password.label }}
                        {{ form.password(class="form-control", placeholder="Password") }}

                        {{ form.confirm_password.label }}
                        {{ form.confirm_password(class="form-control", placeholder="Confirm Password") }}

                        {{ form.submit(class="btn btn-primary btn-lg btn-block text-light w-100 mt-2") }}
                    
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

app/templates/vacation_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-4">
            <h3>Currently editing: {{ vacation.plan_name }}.</h3>
            <form method="post" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.plan_name.label }}
                    {{ form.plan_name(class="form-control", value=vacation.plan_name) }}
                    
                    {{ form.location.label}}
                    {{ form.location(class="form-control", value=vacation.location) }}
                    
                    {{ form.guests.label}}
                    {{ form.guests(class="form-control", value=vacation.guests) }}
                    
                    {{ form.date_leaving.label}}
                    {{ form.date_leaving(class="form-control", value=vacation.date_leaving) }}
                    
                    {{ form.date_returning.label}}
                    {{ form.date_returning(class="form-control", value=vacation.date_returning) }}
                    
                    {{ form.budget.label}}
                    {{ form.budget(class="form-control", value=vacation.budget) }}
                    
                    {{ form.submit(class="btn btn-primary mt-2") }}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

app/templates/vacation_planner.html
{% extends 'base.html' %}

{% block content %}

{% if current_user.is_authenticated %}    

    {% for vacationss in vacations %}

    
    <div class="card-group col-12 col-sm-7 offset-sm-2 flex-column mt-2">
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-8">
                    <div class="card-body d-flex flex-column justify-content-between h-100">
                        <div class="row">
                            <div class="col-md-4 d-flex mt-1">
                                <iframe
                                    style="border:0"
                                    loading="lazy"
                                    allowfullscreen
                                    referrerpolicy="no-referrer-when-downgrade"
                                    src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDJSUgd9hmIf0aQ5NPPM1N45TZSJIFMwuI
                                        &q={{vacationss.location}}">
                                </iframe>
                            </div>
                                <h5 class="card-title">{{ vacationss.plan_name}}</h5>
                            </div>
                            <div class="row">
                                <p class="card-text">{{vacationss.location}}</p>
                            </div>
                            <div class="row justify-content-between mx-3 mt-3">
                                <a href="{{ url_for('home.edit_vacation', vacation_id=vacationss.id)}}" class="btn light-shade border border-secondary" style="width: 50px;"><i class="fas fa-edit"></i></a>
                                <a href="" class="btn btn-danger" style="width: 50px;" data-bs-toggle="modal" data-bs-target="#deleteModal{{vacation_Id}}"><i class="fas fa-trash-alt"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="modal fade" id="deleteModal{{ vacation_Id }}" tabindex="-1" aria-labelledby="deleteModal{{ vacation_Id }}Label" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title text-dark" id="deleteModal{{ vacation_Id}}Label">Delete {{ vacationss }}?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-dark">
            Are you sure you want to delete {{ vacationss.plan_name }}? <br>
            This action cannot be undone.
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <a href="{{ url_for('home.vacationplanner', vacation_id = vacations.id) }}" class="btn btn-danger">Confirm</a>
            </div>
        </div>
        </div>
    </div> 
    {% endfor %}   
{% else %}
<p>Please Sign In to access your Vacation Book</p>
{% endif %}

{% endblock content %}